"""add sync_progress table

Revision ID: 7e357f5fe430
Revises: b595023ef435
Create Date: 2026-04-15 14:42:52.587859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e357f5fe430'
down_revision: Union[str, Sequence[str], None] = 'b595023ef435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_processed_id', sa.Integer(), nullable=True),
    sa.Column('last_page', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_progress')
    # ### end Alembic commands ###
