"""add_token_usage_to_query_logs

Revision ID: ba1c6ca47e51
Revises: fd9deb62477c
Create Date: 2026-05-16 00:47:27.837224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba1c6ca47e51'
down_revision: Union[str, Sequence[str], None] = 'fd9deb62477c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_raw_cache', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('query_logs', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('query_logs', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('query_logs', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.alter_column('sync_progress', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sync_progress', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('query_logs', 'total_tokens')
    op.drop_column('query_logs', 'completion_tokens')
    op.drop_column('query_logs', 'prompt_tokens')
    op.alter_column('product_raw_cache', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
